exec-once = waybar 
exec-once = waypaper --restore
exec-once = clipse -listen 
exec-once = systemctl --user start hyprpolkitagent 
exec-once = hypridle
exec-once = brightnessctl set 60% 
exec-once = swww-daemon 
exec-once = blueman-applet 
exec-once = nm-applet 
