hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("brightnessctl set 60%")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet")
end)
