xwayland {
    force_zero_scaling = true
}

# Match scale 1, fixes most Xorg blur
env = GDK_SCALE,1
env = QT_SCALE_FACTOR,1
env = XCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = NUX_OZONE_PLATFORM_HINT,wayland
